artifactory.algol60.net/uan-docker/stable:
  tls-verify: true
  images:
    cray-uan-config:
    - 0.3.2-20211119162716_7a73212

artifactory.algol60.net/csm-docker/stable:
  tls-verify: true
  images:
    cray-product-catalog-update:
    - 1.3.1
